name: Build and Deploy python-api-dev

on: [ push, pull_request ]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root176g
      DATABASE_NAME: python-api-dev
      DATABASE_PORT: 5432
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      TEST_DATABASE_HOSTNAME: localhost
      TEST_DATABASE_PORT: 5432
      TEST_DATABASE_NAME: python_api_dev_test
      TEST_DATABASE_USERNAME: postgres
      TEST_DATABASE_PASSWORD: root176g
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to ian
        run: echo "Hi Ian"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: run test with pytest
        run: |
          pip install pytest
          pip install requests
          pytest
